name: Build Java version

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths:
      - "java/**"
  # run it during pull request
  pull_request:
    paths:
      - "java/**"

defaults:
  run:
    working-directory: java

jobs:
  build-and-test-code:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      # define the test matrix
      matrix:
        java-version: [17, 18]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: wrapper
          build-root-directory: java

      - name: Archive test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test report
          path: ./java/build/test-results/test
